name: build-linux

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04 ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake .. -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -Donnxruntime_BUILD_UNIT_TESTS=OFF -DBUILD_TEST_EXE=OFF

      - name: Build
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE

      - name: Install
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake --install . --prefix ../install

      - name: BuildNugetPKG
        shell: bash
        working-directory: ${{github.workspace}}/CSharp/libortki
        run: nuget pack libortki-linux.nuspec

      - name: PushPKG
        shell: bash
        working-directory: ${{github.workspace}}/CSharp/libortki
        run: nuget push *.nupkg 54868e95-5638-4dc7-981d-47fc6d76a7cb -source https://www.myget.org/F/magicallibs/api/v3/index.json

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: nncase-${{matrix.os}}-x86_64
          path: ${{github.workspace}}/install
          if-no-files-found: error