name: build-linux

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: seanmiddleditch/gha-setup-ninja@master
  
      - name: Build in docker
        uses: docker://sunnycase/manylinux2010_x86_64
        with:
            args: |
                export PATH=/opt/python/cp37-cp37m/bin:$PATH
                pip install conan==1.58 ninja
                cmake -E make_directory ${{github.workspace}}/build
                cmake .. -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -Donnxruntime_BUILD_UNIT_TESTS=OFF -DBUILD_TEST_EXE=OFF
                cmake --build . --config $BUILD_TYPE
                cmake --install . --prefix ../install

      - name: BuildNugetPKG
        shell: bash
        working-directory: ${{github.workspace}}/CSharp/libortki
        run: nuget pack libortki-linux.nuspec

      - name: PushPKG
        shell: bash
        working-directory: ${{github.workspace}}/CSharp/libortki
        run: nuget push *.nupkg 54868e95-5638-4dc7-981d-47fc6d76a7cb -source https://www.myget.org/F/magicallibs/api/v3/index.json

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: nncase-${{matrix.os}}-x86_64
          path: ${{github.workspace}}/install
          if-no-files-found: error